"""Rename departments_id to department_id

Revision ID: 17f60371b088
Revises: 44e8be63a53f
Create Date: 2026-02-14 18:37:22.741577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f60371b088'
down_revision = '44e8be63a53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('users_departments_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])
        batch_op.drop_column('departments_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departments_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_departments_id_fkey', 'departments', ['departments_id'], ['id'])
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
