"""Add relationship between User and Department

Revision ID: 44e8be63a53f
Revises: 13ee2c50c5f9
Create Date: 2026-02-14 18:31:05.053862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e8be63a53f'
down_revision = '13ee2c50c5f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departments_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['departments_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('departments_id')

    # ### end Alembic commands ###
